export const mappings = {
  "react.js": "react",
  reactjs: "react",
  react: "react",
  "next.js": "nextjs",
  nextjs: "nextjs",
  next: "nextjs",
  "vue.js": "vuejs",
  vuejs: "vuejs",
  vue: "vuejs",
  "express.js": "express",
  expressjs: "express",
  express: "express",
  "node.js": "nodejs",
  nodejs: "nodejs",
  node: "nodejs",
  mongodb: "mongodb",
  mongo: "mongodb",
  mongoose: "mongoose",
  mysql: "mysql",
  postgresql: "postgresql",
  sqlite: "sqlite",
  firebase: "firebase",
  docker: "docker",
  kubernetes: "kubernetes",
  aws: "aws",
  azure: "azure",
  gcp: "gcp",
  digitalocean: "digitalocean",
  heroku: "heroku",
  photoshop: "photoshop",
  "adobe photoshop": "photoshop",
  html5: "html5",
  html: "html5",
  css3: "css3",
  css: "css3",
  sass: "sass",
  scss: "sass",
  less: "less",
  tailwindcss: "tailwindcss",
  tailwind: "tailwindcss",
  bootstrap: "bootstrap",
  jquery: "jquery",
  typescript: "typescript",
  ts: "typescript",
  javascript: "javascript",
  js: "javascript",
  "angular.js": "angular",
  angularjs: "angular",
  angular: "angular",
  "ember.js": "ember",
  emberjs: "ember",
  ember: "ember",
  "backbone.js": "backbone",
  backbonejs: "backbone",
  backbone: "backbone",
  nestjs: "nestjs",
  graphql: "graphql",
  "graph ql": "graphql",
  apollo: "apollo",
  webpack: "webpack",
  babel: "babel",
  "rollup.js": "rollup",
  rollupjs: "rollup",
  rollup: "rollup",
  "parcel.js": "parcel",
  parceljs: "parcel",
  npm: "npm",
  yarn: "yarn",
  git: "git",
  github: "github",
  gitlab: "gitlab",
  bitbucket: "bitbucket",
  figma: "figma",
  prisma: "prisma",
  redux: "redux",
  flux: "flux",
  redis: "redis",
  selenium: "selenium",
  cypress: "cypress",
  jest: "jest",
  mocha: "mocha",
  chai: "chai",
  karma: "karma",
  vuex: "vuex",
  "nuxt.js": "nuxt",
  nuxtjs: "nuxt",
  nuxt: "nuxt",
  strapi: "strapi",
  wordpress: "wordpress",
  contentful: "contentful",
  netlify: "netlify",
  vercel: "vercel",
  "aws amplify": "amplify",

  // Languages
  python: "python",
  py: "python",
  java: "java",
  "c++": "cplusplus",
  cpp: "cplusplus",
  c: "c",
  "c#": "csharp",
  csharp: "csharp",
  go: "go",
  golang: "go",
  rust: "rust",
  kotlin: "kotlin",
  swift: "swift",
  php: "php",
  ruby: "ruby",
  "ruby on rails": "rails",
  rails: "rails",
  r: "r",
  scala: "scala",
  dart: "dart",
  perl: "perl",
  matlab: "matlab",
  elixir: "elixir",
  haskell: "haskell",
  lua: "lua",
  bash: "bash",
  shell: "bash",
  powershell: "powershell",

  // Databases / query languages - devicon has no generic "sql" icon, so
  // point it at the most common relational DB icon instead of 404ing.
  sql: "mysql",
  "ms sql server": "microsoftsqlserver",
  mssql: "microsoftsqlserver",
  sqlserver: "microsoftsqlserver",
  oracle: "oracle",
  mariadb: "mariadb",
  cassandra: "cassandra",
  dynamodb: "dynamodb",
  supabase: "supabase",

  // Frameworks / libraries
  django: "django",
  flask: "flask",
  fastapi: "fastapi",
  spring: "spring",
  "spring boot": "spring",
  laravel: "laravel",
  flutter: "flutter",
  "asp.net": "dot-net",
  dotnet: "dot-net",
  ".net": "dot-net",
  unity: "unity",
  unrealengine: "unrealengine",

  // DevOps / infra / tools
  jenkins: "jenkins",
  terraform: "terraform",
  ansible: "ansible",
  linux: "linux",
  ubuntu: "ubuntu",
  nginx: "nginx",
  apache: "apache",
  grafana: "grafana",
  prometheus: "prometheus",
  vim: "vim",
  vscode: "vscode",
  "visual studio code": "vscode",
  intellij: "intellij",
  androidstudio: "androidstudio",
  xcode: "xcode",
  postman: "postman",
  jira: "jira",
  slack: "slack",
};

export const interviewCovers = [
  "/adobe.png",
  "/amazon.png",
  "/facebook.png",
  "/hostinger.png",
  "/pinterest.png",
  "/quora.png",
  "/reddit.png",
  "/skype.png",
  "/spotify.png",
  "/telegram.png",
  "/tiktok.png",
  "/yahoo.png",
];

export const dummyInterviews: Interview[] = [
  {
    id: "1",
    userId: "user1",
    role: "Frontend Developer",
    type: "Technical",
    techstack: ["React", "TypeScript", "Next.js", "Tailwind CSS"],
    level: "Junior",
    questions: ["What is React?"],
    finalized: false,
    createdAt: "2024-03-15T10:00:00Z",
  },
  {
    id: "2",
    userId: "user1",
    role: "Full Stack Developer",
    type: "Mixed",
    techstack: ["Node.js", "Express", "MongoDB", "React"],
    level: "Senior",
    questions: ["What is Node.js?"],
    finalized: false,
    createdAt: "2024-03-14T15:30:00Z",
  },
];